using ApiForge.Core;
using Npgsql;
using Microsoft.Extensions.Configuration;

namespace ApiForge.Infrastructure;

public sealed class PostgresUserStore(IConfiguration configuration) : IUserStore
{
    private readonly string _cs = configuration["Storage:ConnectionString"] ?? throw new InvalidOperationException("Storage:ConnectionString is required");
    private NpgsqlConnection Open() { var c = new NpgsqlConnection(_cs); c.Open(); return c; }
    private static async Task<UserRecord> Read(NpgsqlDataReader r) => new(r.GetInt64(0), r.GetString(1), r.GetString(2), r.GetString(3), r.IsDBNull(4) ? null : r.GetString(4), r.IsDBNull(5) ? null : r.GetString(5), r.IsDBNull(6) ? [] : (string[])r.GetValue(6), r.GetBoolean(7));
    private const string Select = "SELECT u.id,u.username,u.email,u.password,u.firstname,u.lastname,COALESCE(array_agg(r.name) FILTER (WHERE r.name IS NOT NULL), ARRAY[]::text[]) AS roles,u.enabled FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id";
    public async Task<UserRecord?> Find(string identifier, CancellationToken ct = default) { await using var c=Open(); await using var q=new NpgsqlCommand($"{Select} WHERE u.username=@v OR u.email=@v GROUP BY u.id",c); q.Parameters.AddWithValue("v",identifier); await using var r=await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct)?await Read(r):null; }
    public async Task<UserRecord?> ById(long id, CancellationToken ct = default) { await using var c=Open(); await using var q=new NpgsqlCommand($"{Select} WHERE u.id=@v GROUP BY u.id",c); q.Parameters.AddWithValue("v",id); await using var r=await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct)?await Read(r):null; }
    public async Task<IReadOnlyList<UserRecord>> All(CancellationToken ct = default) { await using var c=Open(); await using var q=new NpgsqlCommand($"{Select} GROUP BY u.id ORDER BY u.id",c); await using var r=await q.ExecuteReaderAsync(ct); var x=new List<UserRecord>(); while(await r.ReadAsync(ct)) x.Add(await Read(r)); return x; }
    public async Task<UserRecord> Add(string username,string email,string password,string? first,string? last,IReadOnlyList<string> roles,CancellationToken ct=default)
    { await using var c=Open(); await using var tx=await c.BeginTransactionAsync(ct); await using var q=new NpgsqlCommand("INSERT INTO users(username,email,password,firstname,lastname,enabled) VALUES(@u,@e,@p,@f,@l,TRUE) RETURNING id",c,tx); q.Parameters.AddWithValue("u",username);q.Parameters.AddWithValue("e",email);q.Parameters.AddWithValue("p",BCrypt.Net.BCrypt.HashPassword(password));q.Parameters.AddWithValue("f",(object?)first??DBNull.Value);q.Parameters.AddWithValue("l",(object?)last??DBNull.Value);var id=(long)(await q.ExecuteScalarAsync(ct))!; await SetRoles(c,tx,id,roles,ct); await tx.CommitAsync(ct); return (await ById(id,ct))!; }
    private static async Task SetRoles(NpgsqlConnection c,NpgsqlTransaction tx,long id,IReadOnlyList<string> roles,CancellationToken ct){await using var clear=new NpgsqlCommand("DELETE FROM user_roles WHERE user_id=@id",c,tx);clear.Parameters.AddWithValue("id",id);await clear.ExecuteNonQueryAsync(ct);foreach(var role in roles){await using var ensure=new NpgsqlCommand("INSERT INTO roles(name) VALUES(@n) ON CONFLICT(name) DO NOTHING",c,tx);ensure.Parameters.AddWithValue("n",role);await ensure.ExecuteNonQueryAsync(ct);await using var add=new NpgsqlCommand("INSERT INTO user_roles(user_id,role_id) SELECT @id,id FROM roles WHERE name=@n ON CONFLICT DO NOTHING",c,tx);add.Parameters.AddWithValue("id",id);add.Parameters.AddWithValue("n",role);await add.ExecuteNonQueryAsync(ct);}}
    public async Task<UserRecord?> SetRoles(long id,IReadOnlyList<string> roles,CancellationToken ct=default){await using var c=Open();await using var tx=await c.BeginTransactionAsync(ct);if(await ById(id,ct) is null)return null;await SetRoles(c,tx,id,roles,ct);await tx.CommitAsync(ct);return await ById(id,ct);}
    public async Task<bool> Remove(long id,CancellationToken ct=default){await using var c=Open();await using var q=new NpgsqlCommand("DELETE FROM users WHERE id=@id",c);q.Parameters.AddWithValue("id",id);return await q.ExecuteNonQueryAsync(ct)>0;}
}

public sealed class PostgresPermissionStore(IConfiguration configuration) : IPermissionStore
{
    private readonly string _cs = configuration["Storage:ConnectionString"] ?? throw new InvalidOperationException("Storage:ConnectionString is required");
    private NpgsqlConnection Open() { var c=new NpgsqlConnection(_cs);c.Open();return c; }
    public async Task<ApiPermissionDto> Add(ApiPermissionDto x,CancellationToken ct=default){await using var c=Open();await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("INSERT INTO api_permissions(content_type_api_id,endpoint,method) VALUES(@c,@e,@m) RETURNING id,created_at",c,tx);q.Parameters.AddWithValue("c",x.ContentTypeApiId);q.Parameters.AddWithValue("e",x.Endpoint);q.Parameters.AddWithValue("m",x.Method);await using var r=await q.ExecuteReaderAsync(ct);await r.ReadAsync(ct);var id=r.GetInt64(0);var created=r.GetDateTime(1);await r.CloseAsync();await Roles(c,tx,"api_permission_roles",id,x.AllowedRoles??[],ct);await tx.CommitAsync(ct);return x with {Id=id,CreatedAt=created};}
    public async Task<ContentPermissionDto> Add(ContentPermissionDto x,CancellationToken ct=default){await using var c=Open();await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("INSERT INTO content_permissions(content_type_api_id,action) VALUES(@c,@a) RETURNING id,created_at",c,tx);q.Parameters.AddWithValue("c",x.ContentTypeApiId);q.Parameters.AddWithValue("a",x.Action);await using var r=await q.ExecuteReaderAsync(ct);await r.ReadAsync(ct);var id=r.GetInt64(0);var created=r.GetDateTime(1);await r.CloseAsync();await Roles(c,tx,"content_permission_roles",id,x.AllowedRoles??[],ct);await tx.CommitAsync(ct);return x with {Id=id,CreatedAt=created};}
    private static async Task Roles(NpgsqlConnection c,NpgsqlTransaction tx,string table,long id,IEnumerable<string> roles,CancellationToken ct){foreach(var role in roles){await using var q=new NpgsqlCommand($"INSERT INTO {table}(permission_id,role_name) VALUES(@id,@r) ON CONFLICT DO NOTHING",c,tx);q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("r",role);await q.ExecuteNonQueryAsync(ct);}}
    public async Task<IReadOnlyList<ApiPermissionDto>> ApiAll(CancellationToken ct=default){await using var c=Open();await using var q=new NpgsqlCommand("SELECT p.id,p.content_type_api_id,p.endpoint,p.method,p.created_at,COALESCE(array_agg(r.role_name) FILTER(WHERE r.role_name IS NOT NULL),ARRAY[]::text[]) FROM api_permissions p LEFT JOIN api_permission_roles r ON r.permission_id=p.id GROUP BY p.id ORDER BY p.id",c);await using var r=await q.ExecuteReaderAsync(ct);var x=new List<ApiPermissionDto>();while(await r.ReadAsync(ct))x.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),new HashSet<string>((string[])r.GetValue(5)),r.GetDateTime(4)));return x;}
    public async Task<IReadOnlyList<ContentPermissionDto>> ContentAll(CancellationToken ct=default){await using var c=Open();await using var q=new NpgsqlCommand("SELECT p.id,p.content_type_api_id,p.action,p.created_at,COALESCE(array_agg(r.role_name) FILTER(WHERE r.role_name IS NOT NULL),ARRAY[]::text[]) FROM content_permissions p LEFT JOIN content_permission_roles r ON r.permission_id=p.id GROUP BY p.id ORDER BY p.id",c);await using var r=await q.ExecuteReaderAsync(ct);var x=new List<ContentPermissionDto>();while(await r.ReadAsync(ct))x.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),new HashSet<string>((string[])r.GetValue(4)),r.GetDateTime(3)));return x;}
    public async Task<ApiPermissionDto?> ApiBy(long id,CancellationToken ct=default)=>(await ApiAll(ct)).FirstOrDefault(x=>x.Id==id);
    public async Task<ContentPermissionDto?> ContentBy(long id,CancellationToken ct=default)=>(await ContentAll(ct)).FirstOrDefault(x=>x.Id==id);
    public async Task<ApiPermissionDto?> Update(ApiPermissionDto x,CancellationToken ct=default){if(x.Id is null||await ApiBy(x.Id.Value,ct) is null)return null;await using var c=Open();await using var q=new NpgsqlCommand("UPDATE api_permissions SET content_type_api_id=@c,endpoint=@e,method=@m WHERE id=@id",c);q.Parameters.AddWithValue("c",x.ContentTypeApiId);q.Parameters.AddWithValue("e",x.Endpoint);q.Parameters.AddWithValue("m",x.Method);q.Parameters.AddWithValue("id",x.Id.Value);await q.ExecuteNonQueryAsync(ct);await using var d=new NpgsqlCommand("DELETE FROM api_permission_roles WHERE permission_id=@id",c);d.Parameters.AddWithValue("id",x.Id.Value);await d.ExecuteNonQueryAsync(ct);foreach(var role in x.AllowedRoles??[]) {await using var a=new NpgsqlCommand("INSERT INTO api_permission_roles(permission_id,role_name) VALUES(@id,@r)",c);a.Parameters.AddWithValue("id",x.Id.Value);a.Parameters.AddWithValue("r",role);await a.ExecuteNonQueryAsync(ct);}return await ApiBy(x.Id.Value,ct);}
    public async Task<ContentPermissionDto?> Update(ContentPermissionDto x,CancellationToken ct=default){if(x.Id is null||await ContentBy(x.Id.Value,ct) is null)return null;await using var c=Open();await using var q=new NpgsqlCommand("UPDATE content_permissions SET content_type_api_id=@c,action=@a WHERE id=@id",c);q.Parameters.AddWithValue("c",x.ContentTypeApiId);q.Parameters.AddWithValue("a",x.Action);q.Parameters.AddWithValue("id",x.Id.Value);await q.ExecuteNonQueryAsync(ct);await using var d=new NpgsqlCommand("DELETE FROM content_permission_roles WHERE permission_id=@id",c);d.Parameters.AddWithValue("id",x.Id.Value);await d.ExecuteNonQueryAsync(ct);foreach(var role in x.AllowedRoles??[]) {await using var a=new NpgsqlCommand("INSERT INTO content_permission_roles(permission_id,role_name) VALUES(@id,@r)",c);a.Parameters.AddWithValue("id",x.Id.Value);a.Parameters.AddWithValue("r",role);await a.ExecuteNonQueryAsync(ct);}return await ContentBy(x.Id.Value,ct);}
    public async Task<bool> RemoveApi(long id,CancellationToken ct=default){await using var c=Open();await using var q=new NpgsqlCommand("DELETE FROM api_permissions WHERE id=@id",c);q.Parameters.AddWithValue("id",id);return await q.ExecuteNonQueryAsync(ct)>0;}
    public async Task<bool> RemoveContent(long id,CancellationToken ct=default){await using var c=Open();await using var q=new NpgsqlCommand("DELETE FROM content_permissions WHERE id=@id",c);q.Parameters.AddWithValue("id",id);return await q.ExecuteNonQueryAsync(ct)>0;}
}
