using ApiForge.Core;
using Npgsql;
using NpgsqlTypes;
using Microsoft.Extensions.Configuration;

namespace ApiForge.Infrastructure;

public sealed class PostgresContentTypeStore(IConfiguration configuration) : IContentTypeStore
{
    private readonly string _cs = configuration["Storage:ConnectionString"] ?? throw new InvalidOperationException("Storage:ConnectionString is required");
    private NpgsqlConnection Open() { var c = new NpgsqlConnection(_cs); c.Open(); return c; }
    private static string Safe(string value) { if (string.IsNullOrWhiteSpace(value) || value.Any(c => !(char.IsLetterOrDigit(c) || c == '_'))) throw new ApiForgeException("Invalid identifier", 400); return value; }
    private static async Task<ContentTypeDto> Read(NpgsqlConnection c, NpgsqlDataReader r, CancellationToken ct)
    {
        var id = r.GetInt64(0); var fields = new List<FieldDto>(); await using var fc = new NpgsqlConnection(c.ConnectionString); await fc.OpenAsync(ct); await using var f = new NpgsqlCommand("SELECT id,name,field_name,type,required,\"unique\",target_content_type,relation_type FROM fields WHERE content_type_id=@id ORDER BY id", fc); f.Parameters.AddWithValue("id", id); await using var fr = await f.ExecuteReaderAsync(ct); while (await fr.ReadAsync(ct)) fields.Add(new(fr.GetInt64(0), fr.GetString(1), fr.GetString(2), Enum.Parse<FieldType>(fr.GetString(3)), fr.IsDBNull(4) ? null : fr.GetBoolean(4), fr.IsDBNull(5) ? null : fr.GetBoolean(5), fr.IsDBNull(6) ? null : fr.GetString(6), fr.IsDBNull(7) ? null : fr.GetString(7)));
        return new(id, r.GetString(1), r.GetString(2), r.GetString(3), r.IsDBNull(4) ? null : r.GetString(4), fields, r.IsDBNull(5) ? null : r.GetDateTime(5), r.IsDBNull(6) ? null : r.GetDateTime(6));
    }
    public async Task<IReadOnlyList<ContentTypeDto>> All(CancellationToken ct) { await using var c = Open(); await using var q = new NpgsqlCommand("SELECT id,name,plural_name,api_id,description,created_at,updated_at FROM content_types ORDER BY id", c); await using var r = await q.ExecuteReaderAsync(ct); var result = new List<ContentTypeDto>(); while (await r.ReadAsync(ct)) result.Add(await Read(c, r, ct)); return result; }
    private async Task<ContentTypeDto?> Find(string sql, object value, CancellationToken ct) { await using var c = Open(); await using var q = new NpgsqlCommand(sql, c); q.Parameters.AddWithValue("v", value); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? await Read(c, r, ct) : null; }
    public Task<ContentTypeDto?> ById(long id, CancellationToken ct) => Find("SELECT id,name,plural_name,api_id,description,created_at,updated_at FROM content_types WHERE id=@v", id, ct);
    public Task<ContentTypeDto?> ByApiId(string apiId, CancellationToken ct) => Find("SELECT id,name,plural_name,api_id,description,created_at,updated_at FROM content_types WHERE api_id=@v", apiId, ct);
    public async Task<ContentTypeDto> Create(ContentTypeDto dto, CancellationToken ct) { await using var c = Open(); await using var tx = await c.BeginTransactionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO content_types(name,plural_name,api_id,description) VALUES(@n,@p,@a,@d) RETURNING id,created_at,updated_at", c, tx); q.Parameters.AddWithValue("n", dto.Name); q.Parameters.AddWithValue("p", dto.PluralName ?? dto.Name + "s"); q.Parameters.AddWithValue("a", Safe(dto.ApiId)); q.Parameters.AddWithValue("d", (object?)dto.Description ?? DBNull.Value); await using var r = await q.ExecuteReaderAsync(ct); await r.ReadAsync(ct); var id = r.GetInt64(0); var created = r.GetDateTime(1); var updated = r.GetDateTime(2); await r.CloseAsync(); foreach (var f in dto.Fields ?? []) { await using var fq = new NpgsqlCommand("INSERT INTO fields(name,field_name,type,required,\"unique\",target_content_type,relation_type,content_type_id) VALUES(@n,@fn,@t,@r,@u,@tc,@rt,@id)", c, tx); fq.Parameters.AddWithValue("n", f.Name); fq.Parameters.AddWithValue("fn", Safe(f.FieldName)); fq.Parameters.AddWithValue("t", f.Type.ToString()); fq.Parameters.AddWithValue("r", (object?)f.Required ?? DBNull.Value); fq.Parameters.AddWithValue("u", (object?)f.Unique ?? DBNull.Value); fq.Parameters.AddWithValue("tc", (object?)f.TargetContentType ?? DBNull.Value); fq.Parameters.AddWithValue("rt", (object?)f.RelationType ?? DBNull.Value); fq.Parameters.AddWithValue("id", id); await fq.ExecuteNonQueryAsync(ct); } await using (var table = new NpgsqlCommand($"CREATE TABLE IF NOT EXISTS ct_{Safe(dto.ApiId)} (id BIGSERIAL PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)", c, tx)) await table.ExecuteNonQueryAsync(ct); await tx.CommitAsync(ct); return new(id, dto.Name, dto.PluralName ?? dto.Name + "s", dto.ApiId, dto.Description, dto.Fields, created, updated); }
    public async Task<ContentTypeDto> Update(long id, ContentTypeDto dto, CancellationToken ct) { var old = await ById(id, ct) ?? throw new ApiForgeException("Content type not found", 404); await using var c = Open(); await using var q = new NpgsqlCommand("UPDATE content_types SET name=COALESCE(@n,name),plural_name=COALESCE(@p,plural_name),description=COALESCE(@d,description),updated_at=CURRENT_TIMESTAMP WHERE id=@id", c); q.Parameters.AddWithValue("n", (object?)dto.Name ?? DBNull.Value); q.Parameters.AddWithValue("p", (object?)dto.PluralName ?? DBNull.Value); q.Parameters.AddWithValue("d", (object?)dto.Description ?? DBNull.Value); q.Parameters.AddWithValue("id", id); await q.ExecuteNonQueryAsync(ct); return (await ById(id, ct))!; }
    public async Task Delete(long id, CancellationToken ct) { var old = await ById(id, ct) ?? throw new ApiForgeException("Content type not found", 404); await using var c = Open(); await using var tx = await c.BeginTransactionAsync(ct); await using var d = new NpgsqlCommand($"DROP TABLE IF EXISTS ct_{Safe(old.ApiId)}; DELETE FROM content_types WHERE id=@id", c, tx); d.Parameters.AddWithValue("id", id); await d.ExecuteNonQueryAsync(ct); await tx.CommitAsync(ct); }
}

public sealed class PostgresContentStore(IContentTypeStore types, IConfiguration configuration) : IContentStore
{
    private readonly string _cs = configuration["Storage:ConnectionString"]!;
    private NpgsqlConnection Open() { var c = new NpgsqlConnection(_cs); c.Open(); return c; }
    private static string Safe(string value) { if (value.Any(c => !(char.IsLetterOrDigit(c) || c == '_'))) throw new ApiForgeException("Invalid identifier", 400); return value; }
    private async Task Ensure(string api, CancellationToken ct) { if (await types.ByApiId(api, ct) is null) throw new ApiForgeException("Content type not found", 404); }
    private static IDictionary<string, object?> Row(NpgsqlDataReader r) { var d = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase); for (var i = 0; i < r.FieldCount; i++) d[r.GetName(i)] = r.IsDBNull(i) ? null : r.GetValue(i); return d; }
    public async Task<IDictionary<string, object?>?> Create(string api, IDictionary<string, object?> values, CancellationToken ct) { await Ensure(api, ct); await using var c = Open(); var keys = values.Keys.Select(Safe).ToList(); await using var q = new NpgsqlCommand($"INSERT INTO ct_{Safe(api)} ({string.Join(',', keys)}) VALUES ({string.Join(',', keys.Select((_,i)=>"@p"+i))}) RETURNING *", c); for (var i=0;i<keys.Count;i++) q.Parameters.AddWithValue("p"+i, values[keys[i]] ?? DBNull.Value); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? Row(r) : null; }
    public async Task<IReadOnlyList<IDictionary<string, object?>>> All(string api, CancellationToken ct) { await Ensure(api, ct); await using var c=Open(); await using var r=await new NpgsqlCommand($"SELECT * FROM ct_{Safe(api)} ORDER BY id",c).ExecuteReaderAsync(ct); var x=new List<IDictionary<string,object?>>(); while(await r.ReadAsync(ct)) x.Add(Row(r)); return x; }
    public async Task<IReadOnlyList<IDictionary<string, object?>>> Search(string api, IDictionary<string, object?> filters, CancellationToken ct) { await Ensure(api,ct); await using var c=Open(); var keys=filters.Keys.Select(Safe).ToList(); var where=keys.Count==0?"TRUE":string.Join(" AND ",keys.Select((k,i)=>$"{k}=@p{i}")); await using var q=new NpgsqlCommand($"SELECT * FROM ct_{Safe(api)} WHERE {where}",c); for(var i=0;i<keys.Count;i++) q.Parameters.AddWithValue("p"+i,filters[keys[i]]??DBNull.Value); await using var r=await q.ExecuteReaderAsync(ct); var x=new List<IDictionary<string,object?>>(); while(await r.ReadAsync(ct)) x.Add(Row(r)); return x; }
    public async Task<IDictionary<string, object?>?> ById(string api,long id,CancellationToken ct){await Ensure(api,ct);await using var c=Open();await using var q=new NpgsqlCommand($"SELECT * FROM ct_{Safe(api)} WHERE id=@id",c);q.Parameters.AddWithValue("id",id);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Row(r):null;}
    public async Task<IDictionary<string, object?>?> Update(string api,long id,IDictionary<string,object?> values,CancellationToken ct){await Ensure(api,ct);await using var c=Open();var keys=values.Keys.Select(Safe).ToList();await using var q=new NpgsqlCommand($"UPDATE ct_{Safe(api)} SET {string.Join(',',keys.Select((k,i)=>$"{k}=@p{i}"))},updated_at=CURRENT_TIMESTAMP WHERE id=@id RETURNING *",c);for(var i=0;i<keys.Count;i++)q.Parameters.AddWithValue("p"+i,values[keys[i]]??DBNull.Value);q.Parameters.AddWithValue("id",id);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Row(r):null;}
    public async Task Delete(string api,long id,CancellationToken ct){if(await ById(api,id,ct) is null)throw new ApiForgeException("Content not found",404);await using var c=Open();await using var q=new NpgsqlCommand($"DELETE FROM ct_{Safe(api)} WHERE id=@id",c);q.Parameters.AddWithValue("id",id);await q.ExecuteNonQueryAsync(ct);}
}
