using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using ApiForge.Core;
using Microsoft.AspNetCore.Mvc.Testing;

namespace ApiForge.ApiTests;

public sealed class ApiTests : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly HttpClient _client;
    public ApiTests(WebApplicationFactory<Program> factory) => _client = factory.CreateClient();
    [Fact] public async Task Register_is_public_and_returns_compatible_envelope() { var response = await _client.PostAsJsonAsync("/api/auth/register", new { username="test-user", email="test-user@example.com", password="password123", firstname="Test", lastname="User" }); Assert.Equal(HttpStatusCode.OK, response.StatusCode); var body = await response.Content.ReadFromJsonAsync<ApiResponse<AuthResponse>>(); Assert.True(body!.Success); Assert.Equal("Bearer", body.Data!.Type); Assert.NotEmpty(body.Data.Token); }
    [Fact] public async Task Protected_route_without_token_returns_envelope_401() { var response = await _client.GetAsync("/api/content-types"); Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode); var body = await response.Content.ReadFromJsonAsync<ApiResponse<object>>(); Assert.False(body!.Success); }
    [Fact] public async Task Content_type_and_dynamic_content_preserve_contract() { var token = await Register(); using var request = new HttpRequestMessage(HttpMethod.Post, "/api/content-types") { Content = JsonContent.Create(new { name="Test Article", apiId="test-article", fields = new[] { new { name="Title", fieldName="title", type="SHORT_TEXT", required=true, unique=false } } }) }; request.Headers.Authorization = new("Bearer", token); var created = await _client.SendAsync(request); Assert.Equal(HttpStatusCode.OK, created.StatusCode); var type = await created.Content.ReadFromJsonAsync<JsonElement>(); Assert.Equal("test-article", type.GetProperty("data").GetProperty("apiId").GetString()); using var add = new HttpRequestMessage(HttpMethod.Post, "/api/content/test-article") { Content = JsonContent.Create(new { title="Hello" }) }; add.Headers.Authorization = new("Bearer", token); var entryResponse = await _client.SendAsync(add); Assert.Equal(HttpStatusCode.OK, entryResponse.StatusCode); var entry = await entryResponse.Content.ReadFromJsonAsync<JsonElement>(); Assert.True(entry.GetProperty("success").GetBoolean()); using var search = new HttpRequestMessage(HttpMethod.Post, "/api/content/test-article/search") { Content = JsonContent.Create(new { title="Hello" }) }; search.Headers.Authorization = new("Bearer", token); var searched = await _client.SendAsync(search); Assert.Equal(HttpStatusCode.OK, searched.StatusCode); }
    [Fact] public async Task Permission_check_uses_role_intersection() { var token = await Register(); using var create = new HttpRequestMessage(HttpMethod.Post, "/api/permissions/content") { Content = JsonContent.Create(new { contentTypeApiId="test", action="READ", allowedRoles = new[] { "EDITOR" } }) }; create.Headers.Authorization = new("Bearer", token); Assert.Equal(HttpStatusCode.OK, (await _client.SendAsync(create)).StatusCode); using var check = new HttpRequestMessage(HttpMethod.Post, "/api/permissions/content/check") { Content = JsonContent.Create(new { contentTypeApiId="test", action="READ", userRoles = new[] { "EDITOR" } }) }; check.Headers.Authorization = new("Bearer", token); var response = await _client.SendAsync(check); var body = await response.Content.ReadFromJsonAsync<ApiResponse<bool>>(); Assert.True(body!.Data); }
    [Fact] public async Task Multipart_media_upload_returns_compatible_metadata() { var token = await Register(); using var form = new MultipartFormDataContent(); form.Add(new ByteArrayContent("hello"u8.ToArray()), "files", "hello.txt"); using var request = new HttpRequestMessage(HttpMethod.Post, "/api/upload") { Content = form }; request.Headers.Authorization = new("Bearer", token); var response = await _client.SendAsync(request); Assert.Equal(HttpStatusCode.OK, response.StatusCode); var body = await response.Content.ReadFromJsonAsync<JsonElement>(); Assert.Equal("File uploaded successfully", body.GetProperty("message").GetString()); Assert.StartsWith("/api/upload/files/", body.GetProperty("data").GetProperty("url").GetString()); }
    [Fact] public async Task Refresh_is_public_and_returns_rotated_tokens() { var id = Guid.NewGuid().ToString("N")[..10]; var response = await _client.PostAsJsonAsync("/api/auth/register", new { username="refresh"+id, email=id+"@example.com", password="password123" }); var body = await response.Content.ReadFromJsonAsync<ApiResponse<AuthResponse>>(); var refresh = await _client.PostAsJsonAsync("/api/auth/refresh", new { refreshToken=body!.Data!.RefreshToken }); Assert.Equal(HttpStatusCode.OK, refresh.StatusCode); var next = await refresh.Content.ReadFromJsonAsync<ApiResponse<AuthResponse>>(); Assert.True(next!.Success); Assert.NotEmpty(next.Data!.Token); }
    [Fact] public async Task User_admin_and_content_delete_routes_return_source_messages() { var token = await Register(); using var users = new HttpRequestMessage(HttpMethod.Get, "/api/auth/users"); users.Headers.Authorization = new("Bearer", token); var userResponse = await _client.SendAsync(users); Assert.Equal(HttpStatusCode.OK, userResponse.StatusCode); var typeRequest = new HttpRequestMessage(HttpMethod.Post, "/api/content-types") { Content = JsonContent.Create(new { name="Delete Type", apiId="delete-type"+Guid.NewGuid().ToString("N")[..6] }) }; typeRequest.Headers.Authorization = new("Bearer", token); var typeResponse = await _client.SendAsync(typeRequest); var type = await typeResponse.Content.ReadFromJsonAsync<JsonElement>(); var typeId = type.GetProperty("data").GetProperty("id").GetInt64(); var delete = new HttpRequestMessage(HttpMethod.Delete, "/api/content-types/"+typeId); delete.Headers.Authorization = new("Bearer", token); var deleted = await _client.SendAsync(delete); Assert.Equal(HttpStatusCode.OK, deleted.StatusCode); }
    private async Task<string> Register() { var id = Guid.NewGuid().ToString("N")[..10]; var response = await _client.PostAsJsonAsync("/api/auth/register", new { username="user"+id, email=id+"@example.com", password="password123" }); var body = await response.Content.ReadFromJsonAsync<ApiResponse<AuthResponse>>(); return body!.Data!.Token; }
}
